repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: [
          src/aivinnet/utils/hashing.py,
          src/aivinnet/utils/dates.py,
          src/aivinnet/utils/parsers.py,
          src/aivinnet/utils/__init__.py,
          src/aivinnet/lib/playlist_maintenance.py,
          --config-file, pyproject.toml,
        ]
        additional_dependencies: [xxhash, unidecode, pendulum]
