"""`--password-reset` must not run before the password salt exists.

Passwords are salted with `serverId`, and `serverId` is generated by
`run_setup`. The tool used to call `setup_sqlite` alone — so on a configuration
directory that did not exist yet, it created the database with an EMPTY salt.

The account it wrote was then unusable the moment a normal start generated the
real `serverId`: the stored hash had been computed against a different salt, and
a password nobody mistyped simply stopped working. Nothing in the output said so.
"""

import pytest


@pytest.fixture()
def virgin_config(tmp_path, monkeypatch):
    """A configuration directory that does not exist yet — the broken case."""
    from aivinnet.settings import Paths, Singleton

    Singleton._instances.pop(Paths, None)
    monkeypatch.setattr("builtins.input", lambda *_a: "admin")
    monkeypatch.setattr("aivinnet.tools.getpass", lambda *_a: "a-new-password")

    yield tmp_path

    Singleton._instances.pop(Paths, None)


def test_the_salt_exists_before_any_password_is_hashed(virgin_config):
    """
    THE guard. An empty `serverId` here means every password written by this
    tool is hashed against the wrong salt.
    """
    from aivinnet.config import UserConfig
    from aivinnet.settings import Singleton
    from aivinnet.tools import handle_password_reset

    Singleton._instances.pop(UserConfig, None)

    handle_password_reset(virgin_config)

    assert UserConfig().serverId, "serverId was empty — passwords would be salted with nothing"

    Singleton._instances.pop(UserConfig, None)
